language: go

go:
  - 1.9.x

services:
  - mongodb

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::6}

install:
  # Setting environments variables
  - export PATH=$PATH:$HOME/gopath/bin
  - export REVEL_BRANCH="develop"
  - 'if [[ "$TRAVIS_BRANCH" == "master" ]]; then export REVEL_BRANCH="master"; fi'
  - 'echo "Travis branch: $TRAVIS_BRANCH, Revel dependency branch: $REVEL_BRANCH"'
  - git clone -b $REVEL_BRANCH git://github.com/revel/modules ../modules/
  - git clone -b $REVEL_BRANCH git://github.com/revel/cmd ../cmd/
  - git clone -b $REVEL_BRANCH git://github.com/revel/config ../config/
  - git clone -b $REVEL_BRANCH git://github.com/revel/cron ../cron/
  - go get -v github.com/revel/revel/...
  - go get -v github.com/revel/cmd/revel
  - go get -v gopkg.in/mgo.v2

before_script:
  - cp ./conf/app.conf.dist ./conf/app.conf
  - sed -i -e 's/REVEL_SECRET/$REVEL_SECRET/g' ./conf/app.conf
  - sleep 15

script:
  - revel test github.com/PolytechLyon/cloud-project-equipe-8 dev.travis

after_success:
  - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  - export REPO=$DOCKER_HUB_USER/cloud-project
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
